# Generated by Django 3.0.8 on 2020-07-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=16)),
                ('passwod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MUNdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField()),
                ('numofprioreditions', models.IntegerField()),
                ('institution', models.CharField(max_length=100)),
                ('socials', models.TextField(max_length=400)),
                ('mun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.User')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('numcom', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=300)),
                ('mun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.User')),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.User')),
            ],
        ),
        migrations.CreateModel(
            name='Deldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.User')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.Delegation')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('agenda', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=200)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.Edition')),
                ('mun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.User')),
            ],
        ),
    ]
