# Generated by Django 3.1 on 2021-06-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('content', models.CharField(max_length=20000)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MUNuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=100)),
                ('institution', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='+91 ', max_length=15)),
                ('description', models.CharField(default='', max_length=300)),
                ('url', models.CharField(default='http://', max_length=200)),
                ('city', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=100)),
                ('institution', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MUN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.munuser')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.user')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('dobmonth', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.committee')),
            ],
        ),
        migrations.CreateModel(
            name='MUNwatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.munuser')),
            ],
        ),
        migrations.CreateModel(
            name='MUNannouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('dateofcreation', models.DateField(auto_now=True)),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.munuser')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MUN', models.CharField(default='', max_length=50)),
                ('committee', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=2020)),
                ('position', models.CharField(default='', max_length=20)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delwatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='MUNbase.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='MUNbase.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.committee')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='mun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.munuser'),
        ),
    ]
