# Generated by Django 3.0.8 on 2020-07-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwod',
            new_name='password',
        ),
    ]
