# Generated by Django 3.1 on 2021-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='countrylist',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
