# Generated by Django 3.0.8 on 2020-07-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0002_auto_20200729_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='agenda',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='edition',
            name='city',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='mundetails',
            name='institution',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='mundetails',
            name='socials',
            field=models.TextField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
