# Generated by Django 3.1 on 2021-06-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0002_committee_countrylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(max_length=400)),
                ('active', models.CharField(max_length=5)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=100)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.agenda')),
                ('defproposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.committeeadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Talklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('minutes', models.CharField(blank=True, max_length=10, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.agenda')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(default='Absent', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VotingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('abstain', models.CharField(max_length=10)),
                ('yes', models.CharField(max_length=10)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.agenda')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.motion')),
            ],
        ),
        migrations.CreateModel(
            name='TalkListSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.agenda')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.talklist')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.participant')),
            ],
        ),
        migrations.AddField(
            model_name='motion',
            name='delproposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.participant'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=10)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.committee')),
            ],
        ),
    ]
