# Generated by Django 3.1 on 2021-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0003_auto_20210619_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='dobmonth',
        ),
        migrations.AddField(
            model_name='participant',
            name='contactnum',
            field=models.CharField(default='0', max_length=15),
            preserve_default=False,
        ),
    ]
