# Generated by Django 3.1 on 2021-07-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0004_auto_20210622_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='seshname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.attendance')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MUNbase.participant')),
            ],
        ),
    ]
