# Generated by Django 3.0.8 on 2020-07-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0004_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mundetails',
            name='edition',
        ),
        migrations.AddField(
            model_name='edition',
            name='edition',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='deldetails',
            name='delegation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MUNbase.Delegation'),
        ),
    ]
