# Generated by Django 3.1 on 2021-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0005_auto_20210707_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='part',
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
