# Generated by Django 3.0.8 on 2020-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0005_auto_20200729_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
