# Generated by Django 3.0.8 on 2020-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0006_user_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mundetails',
            name='numofprioreditions',
            field=models.IntegerField(default=0),
        ),
    ]
