# Generated by Django 3.0.8 on 2020-08-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0008_auto_20200825_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deldetails',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='deldetails',
            name='delegation',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='head',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='mun',
        ),
        migrations.RemoveField(
            model_name='mundetails',
            name='mun',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kind',
        ),
        migrations.AddField(
            model_name='experience',
            name='MUN',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Deldetails',
        ),
        migrations.DeleteModel(
            name='Delegation',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='MUNdetails',
        ),
    ]
