# Generated by Django 3.0.8 on 2020-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0009_auto_20200830_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='committee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
