# Generated by Django 3.1 on 2020-12-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUNbase', '0010_experience_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(default='', max_length=50),
        ),
    ]
